# Introduction {#intro}

이 장에서는 고전적인 게임이론(Classic Game Theory)에 대해서 다룹니다. 이 강의는 수강자들이 게임이론에 대한 사전지식이 전무하다는 가정 하에 이루어집니다.

## Classic Game Theory

### Purpose: Why do we (political scientists) learn game thoery?

1. To understand strategy, which is essential for political actors.

  + Without strategies (plans), we will face random situation of losses.

2. To get a way to formalize social structures.

  + It means that we learn game theory to examine the effects of structures on indiviual decisions.
  + However, the social structures are endogeneous (hard to estimate and formalize their effects).

### Assumptions: What does game theory assume?

1. Actors behave rationally.
1. In Basic Rational Choice Theory (RCT),

  + Actors have goals and they attempt to achieve those goals through specific actions.
  + Briefly, `rational` means that we want something to happen.
  
    + However, morality or normative quality of these goals and actions is not important.
    + We just assume that actors are rational; they have goals, preferances and they act in order to acheive that.
    + Actors must simply be able to compare different alternatives and make choices based on desire to achieve goals.

정리하자면, 게임이론은 행위자들은 원하는 목표가 있고, 그 목표를 달성하기 위해 특정한 행동을 하고자 한다고 가정합니다. 이렇게 목표를 가지고 행동하는 행위자를 "합리적"이라고 합니다.

이러한 행위자들이 합리적으로 행동한다는 것은 그것이 무작위적으로 이루어지는 것이 아니라는 것을 의미합니다. 어떠한 목표를 향한 체계적(systematic) 행위, 선택가능한 여러가지 행동들의 결과로 도출될 가능한 여러 가지 결과들 사이에서 취사선택하는 전략적(strategic) 행위자들의 행태가 어떻게 이루어지는지를 이해함으로써, 우리는 정치의 영역에서 관측되는 다양한 전략적 상호작용의 동학을 이해할 수 있습니다.

또한, 행위자 자신이 통제할 수 없는 외부적 요인들, 즉 사회 구조를 정형화할 수 있습니다. 특히 정치학에서는 개별 행위자들의 행태에 영향을 미치는 사 구조의 효과를 모형화함으로써, 보다 예측가능한 모형을 만들 수 있다는 이점을 가집니다.


### Utilities: Needed to compare outcomes/alternatives for choices

+ We examine utilities someone has.
+ Utility Theory

  + Assuems that actors are faced with choices of possible actions.
  + Each $\color{red}{\text{action}}$ corresponds to the probability of possible outcome.
  
    + However, my choice can yield different $\color{red}{\text{outcome}}$ from expected outcome.
    + Here, $\color{red}{\text{probability}}$ comes.
    
  + Preferences
  
    + Measures the actor's preferences over the outcome combined with the risk involved with achieving an undesirable outcome.
    + To calculate an expected utilities, 
    $\text{pr(E | Action = 1)} \times \text{U(Outcome | Action = 1)}$, then sum across all possible outcomes.

  + Evaluating Utilities
  
    + Begin with outcomes, which are the possible final results of an actor's decision. Outcomes must be exhaustive and mutually exclusive.
    + Assume that ators have preferecnes over sets of possible outcomes (C).
    + Compare preferences between pairs of outcomes.
      + Strong preferences (C$_i$ > C$_j$); greater
      + Weak preferences (C$_i$ $\geq$ C$_j$); better than equal
      + indifferent preferences (C$_i$ = C$_j$); equal

  + To rank the preferences, we need following:
                 
    1. Completeness: An ordering is complete iff (if and only if) for all pairs of outcome.
    
      + It is necessary assumption so that actors can make comparisons across all pairs of outcomes.
      + Everybody knows the preference ordering for themselves.
      
    2. Transitivity: An ordering if transitive iff C$_i$ $\geq$ C$_j$ $\geq$ C$_k$, C$_i$ $\geq$ C$_k$.
    
      + If one outcome (C$_i$) is at least as good as a second (C$_j$), and the second outcome (C$_j$) is at least as good as a third (C$_k$) $\rightarrow$ C$_i$ $\geq$ C$_j$ $\geq$ C$_k$, C$_i$ $\geq$ C$_k$.
      
  + Importance of Completeness and Transitivity
    + Allows prefrences to be ordered for each other.
    + Ordinal preferences can then be used mathematically.
      + The higher number represents greater preference than the lower number.

### Ordinal Preferences

+ Representation of preferences

  + We can use descending sequence of numbers to reflect ordinal preferences.
  
    + Largest assigned to most preferred outcome.
    + Smallest assigned to least preferred outcome.
    + Indifferent assigned to equal preferred outcome.
    
여기서 착각하지 말아야 하는 것은, 선호가 있기 때문에 효용(utilities)을 알 수 있는 것이지, 효용의 크기에 따라 선호가 결정되는 것은 아니라는 점이다. 

효용을 계산함으로써, 행위자는 그들의 선택할 행동에 따른 가능한 (혹은 장정적인) 결과들을 비교할 수 있게 된다.

효용이론은 행위자들이 가능한 여러 행동들의 선택지를 마주하고 있다고 가정하며, 각각의 행동은 그 행동의 가능한 결과를 얻을 '확률'에 대응한다고 가정한다.

  + 확률이라고 말하는 이유는 때로는 어떠한 결과를 기대하고 선택하였지만 그 결과를 얻지 못할 수도 있기 때문이다.
  + 이처럼 효용이론에서 중요한 개념은 $\color{red}{\text{행동, 결과}}$, 그리고 $\color{red}{\text{확률}}$이다.
  
효용이론은 기대효용(expected utility)라는 개념을 제시하고 있는데, 이는 어떠한 행동이 취해질 때 기대하는 결과를 얻을 확률과 그 행동을 통해 얻을 것이라고 예상되는 효용의 곱한 뒤, 이처럼 가능한 모든 결과들의 효용을 더한 결과로 측정한다.

  + 즉, 동시사건이다. 어떤 행동을 취하는 것은 개인의 선택이지만 그 행동의 기대한 결과가 실제로 나타나는 것은 사회 구조 등과 같은 외부적 요인의 영향을 받기에 확률적이다. 
  + 우리가 선택한 행동에 따른 결과들은 모든 가능한 결과들이어야 하며(exhaustive), 서로 중복되지 않아야 한다(mutually exclusive).
  + 선호들을 줄세우기(ordering) 위해서 우리는 선호에 대해 두 가지 가정을 세운다.
  
    1. 완전성: 모든 행위자들은 자신의 선호순위를 알고 있다.
    2. 이행성: 선호는 이행적이다. A $\geq$ B $\geq$ C라고 하면, A $\geq$ C이다.
  
  + 이 두 가정 덕분에 우리는 선호의 순위를 매길 수 있고, 나아가 순위적 선호들을 수학적으로 사용할 수 있게 된다. 즉, 큰 숫자는 작은 숫자보다 더 큰 선호를 나타낸다는 것이다.

### Utility Functions

+ Combine choices of the actor with outcome, ordinal preferences, and other factors.

  + Other factors are out of control of actors.
  + We call it as `states of the world`, and it is exogeneous.

+ Used to predict actions, and derive equilibria.

  + We want to know what an action will do, and what we can predict.

+ Any decision problem can be described formally.

  + A set of Actions (A), and one of them chosen.
  + States of the world (S)
  + Outcomes or Consequences (C)
  + Preference ordering (P), which is complete, transitive, and fixed.

+ Von Neumann-Morgenstern's Utility Function

  + Used to calculate expected utilities for particular action (A).
  + $\text{EU(A)} = \sum_{\text{all S}}pr(S)\times u[C(S, A)]$.
  
    + `pr` is probability, and `A` is a set of avaiable actions.
    + $[C(S, A)]$ is an outcome for an action an actor chosen under certain state.
    
+ Example: What do we drink?

  + Available choices: Coke, Diet coke, and Sprite.
  
  + Assumption
  
    + We need caffeine and sugar to wake up, and if you cannot have both, you want caffeine.
    + This is an ordinal preference: Coke > Diet > Sprite
    
      + Utility: u(C) = 1, u(D) = 0.4, u(S) = 0
      
    + Additional information: States of the world by assumption
    
      + Soda machine sometimes gives Coke when you push Sprite button.
      + However, when you push Diet coke button, you get Diet coke with 100\%.
      
    + We have theories to guide to set these probabilities in actual research.
    
    + The outcomes are exhaustive, and mutually exclusive: sum of the probability of possible outcomes is 1.
    
Coke Slot | Diet coke slot  | Sprite Slot  | Probability
|:------------:|:---------------:|:------------:|:-----------:|
       Coke      | Diet coke       | Sprite       |  0.3
       Coke      | Diet coke       | Coke         |  0.15
       Sprite    | Diet coke       | Coke         |  0.2
       Sprite    | Diet coke       | Sprite       |  0.3
  Table: What do we drink
  
And we can calculate several possible probabilities: $Pr(\text{Coke | Press Coke}) = 0.45, Pr(\text{Sprite | Press Coke}) = 0.55, Pr(\text{Sprite | Press Sprite}) = 0.65$.
      
  + Then, calculate the expected utilities of the cases; Coke, Diet coke, and Sprite.

$$\begin{aligned} \text{EU(Press Coke)}=&Pr(\text{Coke | Press Coke})\times u(\text{Coke})\\
    &+ Pr(\text{Diet coke | Press Coke})\times u(\text{Diet coke})\\
    &+ Pr(\text{Sprite| Press Coke})\times u(\text{Sprite})\\
    &= 0.45 \times 1 + 0 \times 0.4 + 0.55 \times 0 = 0.45
    \end{aligned}$$
    
$$\begin{aligned} \text{EU(Press Diet coke)}=&Pr(\text{Coke | Press Diet coke})\times u(\text{Coke})\\
    &+ Pr(\text{Diet coke | Press Diet coke})\times u(\text{Diet coke})\\
    &+ Pr(\text{Sprite | Press Diet coke})\times u(\text{Sprite})\\
    &= 0 \times 1 + 1 \times 0.4 + 0 \times 0 = 0.4
    \end{aligned}$$
    
$$\begin{aligned} \text{EU(Press Sprite)}=&Pr(\text{Coke | Press Sprite})\times u(\text{Coke})\\
    &+ Pr(\text{Diet coke | Press Sprite})\times u(\text{Diet coke})\\
    &+ Pr(\text{Sprite| Press Sprite})\times u(\text{Sprite})\\
    &= 0.35 \times 1 + 0 \times 0.4 + 0 \times 0.65 = 0.35
    \end{aligned}$$
    
With these expected utilities, we would expect that it would choose to press coke to acheive our goal.

효용함수는 행위자의 선택과 그 선택을 하게끔 만든 선호의 순위, 선택의 결과, 그리고 그 이외의 요인들로 구성된다. 이때, 이외의 요인은 행위자의 통제 밖의 요인들로 정치학에서 보자면 사회구조와 같은 것들이다.

우리는 효용함수를 이용해서 행위자들이 어떤 행동을 할 것인지를 예측하고자 하고, 나아가 균형점을 찾고자 한다.

  + 균형이란 행위자들이 자신의 행동을 바꾸지 않는 상태라고 할 수 있다.
  + 일단, 콜라, 다이어트 콜라, 스프라이트의 예제에서는 균형까지는 다루지 않고 기대효용을 계산하는 방법과 그렇기에 행위자가 어떠한 선택을 할지 예측하는 과정을 살펴보고 있다.
  + 콜라를 눌렀을 때의 기대효용이 가장 크므로 (0.45 > 0.4 > 0.35) 우리는 행위자들이 그 자신의 선호순위와 결과로부터 얻을 수 있는 효용, 그리고 그 일이 발생할 확률을 알고 있는 한 콜라 버튼을 누를 것이라고 예측할 수 있다.

### Specifying a Game

+ Previous example is a good illustration of decision theory.

  + Evaluation of multiple choices by a single actor.
  
+ Game theory involves evaluating choice of an actor conditioned on a choice made by another actor.

  + Each actor's decision depends on the choice made by others.

+ Types of game structure

  + Normal game: Often used to model decisions made simultaneously.
  
    + Example: Prisoner's Dilemma or Chicken Game
    
  + Extended game: Often used to model decisions made sequentially.
  
    + Majority of games in political science are extended game.
    + Thus, sequence matters. Simultaneous actions / games are hardly observed.
    + Example: Detterance in IR
    
Assumed perfect information and fixed choices are not realistic. $\rightarrow$ An actor may have private information.

  + Perfect information
  
    + All information sets are known by all actors. 
    + Actor possess information about all choices made previously.
  
  + Complete information
  
    + Occuring when all actor possess information about all player's payoffs.
    + Preferences are common knowledge.
  
  + Imcomplete information
    
    + Occuring when some information is private.

사회학의 결정이론과 게임이론의 차이는 단순하다. 결정이론은 단일 행위자가 할 수 있는 여러 가지 결정에 대해 관심을 가지지만, 게임이론은 여러 행위자들의 전략적 상호작용에 관심을 가지고 있다.

게임은 두 행위자가 동시에 선택을 진행하는 정규형(normal)과 행위자들이 순차적으로 행동을 선택하는 확장형(extended)로 구분할 수 있다.

  + 정치학에서는 대개 확장형 게임에 관심을 갖는다.
  + 두 행동이 동시에 일어나는 사건 자체가 관측이 어렵고, 만약에 우리가 관측하였다 하더라도 실제로 우리는 두 행동이 과연 동시에 일어났는지는 알 수 없다.
  
    + 즉, 정치학에서의 게임이론은 확장형으로, 행위자들의 순차적인 전략적 행동에 주목한다.
    + 그리고 게임이론에서 가정할 수 있는 완전한 정보와 확실한 정보도 정치적 현상에서는 적용되기 힘들다.
    
      + 과연 모든 행위자들이 서로의 이전 선택에 대한 정보를 완전하게 갖추고 있고,
      + 각자의 선낵에 따른 보수(payoffs)가 얼마나 될지 확실하게 아는 경우가 얼마나 될까?

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
