# What is International Relations and Games of International Interaction? {#ch3}

> 읽을 자료  

> 1. FLS의 Chapter 2.  

> 2. Ikenberry. After Victory 중에서 Ch.2. "Varieties of Order: Balance of Power, Hegemonic, and Constitutional."

> 3. FLS "Primer on Game Theory." [Special Topic]

> 4. U.N. Charter

> 5. Stewart, P. 2014. “The Unruled World: The Case for Good Enough Global Governance.”

## IR의 거대이론(Grand theories)

[제2장](#intro)에 이어서 IR의 거대이론들을 살펴보는 것에서 시작해보자. 현실주의, 자유주의, 그리고 구성주의가 대표적이라고 할 수 있다.

### 현실주의

현실주의에서 주요 행위자는 국가이다. 현실주의는 국가의 최우선 목표가 생존(survival)이라고 보고 다른 국가들의 의도에 대한 불확실성 속에서 이러한 생존의 추구는 힘의 추구로 이어진다고 주장한다. 따라서 경성 권력(hard power)의 일환으로서 군사력(military power)을 갖추는 것은 국가들로써는 가장 중요한 문제가 된다. 동시에 국가들은 절대적 이득(absolute gains)보다는 상대적 이득(relative gains)을 더 중요하게 고려할 것이라고 본다.

  + 상대적 이득과 절대적 이득
  
    + 현실주의자들은 국제정치는 재분배와 거래의 문제에 있어서 제로섬 게임이라고 본다.
    
    + 따라서 다른 국가들의 의도가 확실하지 않고(다른 국가를 속일 수 있고), 상대적으로 다른 국가가 자국보다 더 많은 이득을 볼 수 있다는 조건 하에서 협력보다는 갈등이 나타날 확률이 높다.
    
  + 힘의 분포(Distribution of capabilities)가 중요하다.
  
    + 패권(hegemony)/일극(unipolarity) 체제와 양극체제(bipolarity)가 다극 체제(multipolarity)보다 더 안정적일 것이라고 주장하게 된다.
      
      + 다극 체제와 안정성에 관한 논의는 Ikenberry에서 좀 더 자세히 살펴보도록 하자.
    
    + 이러한 현실주의자들의 입장은 중국을 위협으로 보느냐에 대한 [존 미어샤이머의 인터뷰](http://youtu.be/r9TNhx85uLA)에서 살펴볼 수 있다.
    
이러한 현실주의자들에게 국제관계에 있어서 행위자들의 상호작용이란 보다 갈등적 상황(전쟁, 분쟁 등)에 초점을 맞출 필요가 있고, 제도는 행위자들의 근본적인 목적과 그에 입각한 행위를 변화시킨지는 못하는 부수적인 것에 지나지 않게 된다.

### 자유주의

자유주의는 인간의 본성은 기본적으로 선하다는 가정에서 출발한다. 따라서 이들은 생존이 중요하기는 하지만 많은 국가들은 생존을 넘어서 경제성장과 같은 번영의 문제에 초점을 맞추어 움직일 것이라고 기대한다.

  + 자유주의자들에게 군사력이란 결국 한정된 효용(limited utility)을 가지고 있을 뿐이다.
  
  + 이들은 연성 권력(soft power)가 더 중요할 수 있다고 본다.
  
자유주의자들에게 국가들은 심지어 국제체제의 무정부 상태라는 조건 하에서도 협력할 수 있는 존재들이다(임마누엘 칸트).

  + 미래의 그림자(Shadow of the future)
    
    + 국제관계에서 상호작용은 일회성이 아다.
    
    + 따라서 국제관계의 행위자들은 갈등보다는 서로 협력을 통해 서로 이득을 보고자 할 것이다.
  
  + 즉, 현실주의자들과는 달리 자유주의자들은 상대적 이득보다는 절대적 이득(absolute gains)을 강조한다.
  
  + 집단행동의 문제를 해결하기 위해 국제관계의 행위자들은 함께 행동할 유인(incentives)를 가지게 된다.

심지어 자유주의자들에게는 비국가 행위자(non-state actors)도 국제정치에서 중요한 역할을 수행하는 존재들이다. 즉, 자유주의자들은 국제제도, 초국적 옹호 네트워크(transnational advocacy networks) 등의 역할이 국제관계의 양상에 미치는 역할에 주목한다.

그렇다면 자유주의자들에게 국제관계에 있어서 이익이란? 현실주의자들과 달리 단일한 것(=survival)이 아니다. 그리고 상호작용에 있어서도 갈등적 양상뿐 아니라 협력적 양상에 대해서도 관심을 가진다. 나아가 이들은 그러한 협력에 있어서 존재하는 다른 국가들의 의도를 알 수 없으며(uncertainty), 서로의 약속을 강제할 권위체가 부재하다는 문제(anarchy $\rightarrow$ commitment problem)를 제도로 해결하고자 한다. 따라서 자유주의자들에게 국제제도는 그에 속한 국가들 간의 정보 교류가 이루어지고 공통의 규범과 규칙을 제약함으로써 행동의 투명성(transparency)을 제고하는 주요 장치라고 할 수 있다.

### 구성주의

구성주의자들은 국제관계에서 이익이란 결국 사회적 상호작용(social interaction)의 결과물이라고 본다. 따라서 이들에게 국가의 행태란 규범, 신념, 그리고 정체성에 의해서 형성되는 것이다. 국제적 상호작용은 국가들에게 이러한 규범, 신념, 정체성을 "사회화"(socialize)하는 과정이다.

  + 그러나 규범은 시간에 걸쳐 변화할 수 있다.
  
  + 구성주의자들의 이와 같은 개념은 국가들의 이익과 관행(practices)의 변화를 설명하는 데 도움을 준다.
  
    + 예를 들어, 인권의 침해나 기후변화와 같은 사례들을 생각해볼 수 있다.
    
    + 인권과 기후변화에 대한 규범 및 관행들은 시간이 지나면서 구체화된, 국가들의 이해관계가 변화된 사례들이다.
    
구성주의자들에게 관념과 담론은 매우 중요하다. 왜냐하면 국제정치에서의 동일한 구조는 서로 다른 국가들에게 서로 다른 시점에서 다른 의미를 지니기 때문이다. 예컨대, A라는 국가는 무정부 상태 하에서 현실주의자가 주창한 것처럼 갈등적 상황, 생존을 최우선 이익이라고 추구할 수 있다. 반면 B라는 국가는 같은 시기에 같은 무정부 상태라는 조건 하에서도 번영을 추구하며 협력적 행태를 보일 수 있는 것이다. 이러한 맥락에서 Wendt는 "무정부 상태란 국가들이 구성해 가는 것"이라고 주장하였다.

그러나 이론적 분석틀로서 구성주의는 많은 어려움을 가지고 있다. 관념, 규범, 정체성, 그리고 변화 중에 무엇이 원인이고 무엇이 결과인지 알 수 없다는 잠재적 내생성(possible endogeneity)의 문제가 대표적이다.

정리하자면, 구성주의자들에게 이익은 고정된 것이 아니라 관념, 규범, 정체성 등에 의하여 변화할 수 있는 것이다. 그리고 국제관계의 행위자들 간 상호작용은 이러한 관념, 규범, 정체성의 변화를 각 행위자들에게 '사회화'하는 기제이기 때문에 중요하다. 자유주의자들과 마찬가지로 국제제도도 사회화의 기제라는 맥락에서 구성주의자들에게는 중요한 분석 대상이다.

## 거대이론들에 대한 평가

하지만 이러한 거대이론들이 왜 국제관계를 연구하는 학자들로부터 점차 관심을 잃게 되었을까? 거대이론들은 대개 국제적 수준, 혹은 구조적 수준에서 독립변수들을 설정하고 있지만 그것들은 대개 거의 변하지 않는 것들이다. 

  + 몇몇 학자들은 여전히 거대이론들로 세계정치의 현상들을 분석하고자 하고 있다(예를 들면, 미어샤이머?). 그리나 거대이론들을 분석틀로 사용하는 이들도 그것을 직접적인 현상 분석에 적용하지는 않는 추세다.

이는 세계정치 속에서 우리가 관심을 가지는 현상, 즉 결과들이 상대적으로 새롭고, 변화하는 것에 비하여 본다면 과연 결과를 설명하기에 충분한 열쇠(key)인지 의구심이 들게 하는 것이다. 때문에 국제관계 학자들은 최근 분석의 수준을 국내정치, 그리고 개별 지도자 수준으로 옮겨갈 필요성을 제기하고 있다.

거대이론들은 실제로 냉전의 종식(1989-1990년)을 설명하지 못했다. 이를 계기로 많은 학자들이 이론의 범주를 중범위 이론(mid-range theories)으로 전환하게 되었다. 왜 체계이론/거대이론들은 냉전의 종식을 설명하지 못했던 걸까?

## 정치적 질서의 다양성 (Varieties of Political Order)

Ikenberry는 세계적 질서(world order)의 등장에 대해 어떻게 이해할 수 있을지에 관심을 가지고 있었다. 이러한 세계적 질서에 대한 개념은 Hadley Bull에서 비롯되었다. 국제관계에서 정치적 질서(political order)란 "일단의 국가들 간 존재하는 통치의 장치 (the governing arrangements among a group of states)"를 의미하며 규칙(rules), 제도(institutions) 등을 의미한다.

Ikenberry는 국제적 질서의 세 가지 중요한 교리(tenets)는 바로 (1) 조직화의 원칙(organizing principles), (2) 힘에 대한 제한(restraints on power), (3) 안정성의 근원(source of stability)라고 주장하고 있다.

  + 이 중 Ikenberry가 말하는 힘(power)이란 FLS에서 정의하는 개념으로 이해해볼 수 있다.
  
    + A라는 행위자가 B라는 행위자가 하지 않을 어떠한 행동을 하게끔 할 수 있는 능력
    
    + 또는 B라는 행위자에게 양보를 강요할 수 있는 능력
    
    + 혹은 A가 양보하지 않아도 되게끔 하는 능력
    
그리고 위의 Ikenberry의 질서의 세 가지 유형은 다음과 같은 말로 바꾸어 설명할 수 있다.: (1) 규칙에 따르는(constitutional)[^3-1], (2) 세력 균형의, (3) 패권적 질서. 즉, 개별 국가들이 어떠한 규칙에 따르는 유형의 질서가 존재하고, 혹은 힘을 가진 여러 국가들이 서로를 견제하는 질서가 있을 수 있으며, 마지막으로 강력한 하나의 국가가 주도하는 질서가 존재할 수 있다는 것이다.
  
그렇다면 현재 세계의 질서는 어떠한 유형의 질서라고 할 수 있을까? 이것은 사실 관점에 따라 다른 평가가 가능할 것이다. 그리고 어떠한 질서라고 정의할 때, 우리는 그 질서들에 대한 여러 가지 질문들을 던져볼 수 있다. 예를 들어,

  + 세력 균형 질서라고 한다면? 
  
    + 우리는 어떻게 약소국들이 강대국에 편승(bandwagoning)하는 현상을 설명할 수 있는가?
    
    + 우리가 현재 살펴볼 수 있는 균형화의 사례로는 무엇이 있을까?
    
    + 균형화에 대해 Snyder가 제기할 수 있는 비판으로는 어떠한 것이 있을까?
    
      + 왜 국가들은 미국의 힘이 부상함에도 불구하고 이를 견제하지 않았을까?
  
  + 패권적 질서라고 한다면?
  
    + 현재 패권국은 어떤 국가일까?
    
    + 패권적 질서는 변화를 허용할까? 허용하지 않는다면, 패권국은 과연 변화를 추구하는 '도전자'와 어떠한 상호작용을 맺게 될까?
    
  + 규칙을 준수하는 질서라고 한다면?
  
    + Ikenberry에게 이러한 질서는 무엇을 의미하는 걸까?
    
    + Ikenberry는 규칙준수의 질서에 대해 세 가지 요소들이 필요하다고 주장하였다.
    
      1. 원칙에 대한 합의가 공유되어야 하고,
      
      2. 규칙과 제도들은 **각 국가들의 힘의 행사에 대해 제한할 수 있는 규제력(binding)**을 가져야 하며,
      
      3. 쉽게 변화되지 않아야 한다는 것이다.
  
  + 듣기에는 좋아보인다. 그런데 이러한 Ikenberry가 말하는 규칙준수의 질서가 세계정치에 실재하려면 어떤 조건들이 필요할까? 과연 이러한 질서로 세계정치를 설명할 수 있을까?
  
  + 규칙준수의 질서에서 가장 주요한 목적은 바로 '승리'로부터 얻어지는 보상을 줄이는 것이다.
  
    + 즉, 어느 국가도 이겨봐야 뭘 많이 얻을 수 없다는 것을 알면 굳이 이기고 지는 것에 연연하지 않게 될 것이다.
    
그런데 국제관계에서 '승리', '이긴다'라는 것은 무엇을 의미할까? 우리는 약 세 가지 정도의 경우를 생각해볼 수 있다.

  1. 강압(coercion)이다. 위협 등의 수단을 통해 승리하여 상대방에게 비용을 부과할 수 있는 보상을 얻는 것이다. 무력을 사용한 위협이 종종 강압의 대표적인 사례라고 할 수 있다. 또 다른 강압의 유형으로는 제재(sanction) 등이 있다고 할 수 있다.
  
  2. 외부옵션(outside options)이다. 특정한 행위자와 거래를 하지 않을 수 있는 대안이 존재할 경우를 말한다. 간단하게 말하자면, 상대방은 나와 거래를 해야만하지만, 나는 그 이외에도 다른 대안들이 많을 때, 나는 거래의 비교우위를 가지게 된다. 즉, 테이블을 박차고 나올 수 있는 능력을 말한다.
    + 국제관계에서 동맹을 변경하거나 경제협력 파트너를 변경하는 등의 옵션을 생각해볼 수 있다. 과연 누가 파트너를 바꿀까? 좀 더 강한 쪽(잃을 게 적은 쪽, 혹은 잃어도 더 버틸 여력이 되는 쪽)이다.
    
  3. 의제설정의 힘(agenda-setting power)이다. 선점을 통해 얻는 이점을 의미하는 것으로 아마도 이 개념이 가장 Ikenberry가 말하는 규칙준수 체계를 이해하는 데 도움이 될 것이다.
    + 우리는 종종 미국이라는 초강대국이 가지는 의제선점의 힘을 목격하고는 한다.
      + 예를 들어, 남북관계에 중요한 여러 사항들에 대해 미국이 주요 의제를 먼저 제시하고 다른 당사자들은 이를 후속적으로 따라가는 경우를 종종 볼 수 있다.
    + 의제를 설정하는 행위자를 제약할 수 있는 것은 무엇인가
    
'행위자'를 제약할 수 있는 것, 그것이 바로 제도이다. 제도는 다음과 같은 것들을 통하여 국제관계의 행위자들의 행동을 제약한다.

1. 행위의 기준을 설정한다. 규범 또는 헌장 등을 통해 시간에 걸쳐 명시적으로 규칙을 수립할 수 있다.

2. 그렇게 수립된 규칙을 다른 국가들로 하여금 순응(comliance)하게 하고, 그 순응을 정당화하기도 한다. 제도에 속한 구성원들은 다른 구성원들이 제도의 규칙에 순응하는지 서로를 감시할 수 있다(선거, 핵무기 생산 등).

3. 의사결정에 드는 비용을 감소시켜, 제도가 없는 의사결정보다 제도에 기초한 의사결정을 선호하게 만든다.

4. WTO, 지역무역협정(Regional Trade Agreements) 등과 같은 분쟁해결 기제들을 통해 행위자들 간 분쟁을 해결하기도 한다.

## 국제적 상호작용의 게임 (Games of International Interaction)

### 대체 게임이론이란 무엇인가?

게임이론에 대해서 처음 접하는 사람들이 가지고 있는 개략적인 연관 관념들을 보면, 수학적 기호나 그로 이루어진 복잡한 공식들이 있다. 분석하고자 하는 현실세계의 정치현상을 정교하게 들여다보기 위해서는 게임 그 자체에 다양한 행위자들과 복잡한 상호작용을 고려해야 한다. 문제는 그것들을 모두 줄글로 표현할 수 없기 때문에 모든 사람들이 합의할 수 있는 공약(connotaiton)에 기초하여 함축적인 표현으로 사용하게 된다는 것이다. 그 결과, 전 세계 모든 사람들이 오해 없이 받아들일 수 있는 공통의 약속---수학적 기호를 이용하게 되는 것이다. 보다 직관적으로(straightforward), 행위자, 선택, 전략들에 값(values)이나 숫자(numbers)를 붙여서 전략을 살펴볼 때, 구분이 더 쉽고 이해하기 편하게 한 것일 뿐이다.

  + 하지만 게임이론의 깆에 놓여 있는 논리는 결코 수학적인 것만은 아니다.
  
  + 오히려 게임이론을 관통하는 하나의 관념은 바로 전략적 상호작용(strategic interaction)이라고 할 수 있다.
  
    + 그런데 대체 이 '전략적 상호작용'이라는 것이 무엇을 의미하는 것일까?
    + 간단하게 얘기하자면, 다른 행위자를 고려한 의사결정의 과정(process of joint decision making)이라고 할 수 있다.
      + 예를 들어, 핵무기 개발, 집단 안보, 국제조약의 이행 등은 IR에서 살펴볼 수 있는 전략적 상호작용의 사례들이다. 
      + 위와 같은 상호작용은 어디까지나 하나의 행위자가 자신의 선호만을 고려해서 이루어지는 것이 아니다.
      + 여기서 살펴볼 수 있는 '상호작용'이 함축하고 있는 한 가지 전제, 최소 둘 이상의 행위자들이 존재해야 한다는 것이다.

  + 그럼 게임(game)은 무엇일까? 게임은 바로 모델(models)이다.[^3-2]
  
  + 논리적으로 현실세계를 단순하게 재구성하는 하나의 방법이 모델이라고 할 수 있다.
  
    + 모델은 과학적 연구를 수행함에 있어서 이론적(논리적) 시각을 따라 현실세계에 접근하는데 도움을 주는 길잡이의 역할을 수행한다.
    + 모델은 현실세계와의 상호조응성(isomorphism)을 가지고 있다.
      + 즉, 모델은 현실세계의 모습을 이론적으로 재구성한 분석기제(oversimplified and omitted reality)와 같다.
      + 연구자는 특정한 이론에 따라 실제 현상의 표출양상 가운데 가장 중요하다고 판단되는 것만을 선택해 그들 간의 관계양상을 모델로 표현한다.
      + 따라서 모델과 현실세계의 상호조응성은 부분적이자 불완전하므로 같은 현상에 대한 서로 다른 모델들이 무수히 존재할 수 있다.
      
    + 즉, 게임도 모델이기 때문에 게임도 항상 똑같은 형태를 가지지는 않는다.---게임은 유연하며(flexible), 가변적이다(adaptable).
    
### 게임의 요소

조금 더 깊게 들어가보자. FLS은 게임이론에 있어서 게임의 주요 요소로 행위자(actors), 선택(choices), 결과(outcomes), 선호(preferences), 전략(strategies), 해결방안(혹은 해, solution) 등을 소개하고 있다.

  + 행위자
    + 분석하고자 하는 게임에 얼마나 많은 행위자들이 존재하는지를 파악하는 것은 필수적이다.
    + 당연하게도, 행위자가 많아질수록 게임이 조금 더 복잡해진다.
  
  + 선택
    + 행위자들은 몇 가지의 가능한 선택지를 가지고 있는지 역시 파악해야 한다. 
    + 행위자들이 몇 개의 선택지를 가질 것이냐는 전적으로 현실세계를 반영하여 모델을 설계하는 연구자의 재량에 달려 있다. 
    + 마찬가지로 선택지가 많을수록 게임을 푸는 방법은 복잡해진다.
  
  + 결과
    + 이렇게 파악한 행위자와 그들의 선택지 간 결합(combination)이 어떠한 결과를 가져오는지 이해해야 한다. 
    + 이 결과야 말로 우리가 이해하고자 하는 경험적 사건이라고 할 수 있을 것이다.
    + 예를 들면, 두 국가 간의 핵무기 군비경쟁이라던가, 평화조약의 채택이라던가 등.
    
  + 선호
    + 선호는 행위자들이 그들의 선택에 순위를 매기는 방법이다. 
    + 선호야말로 우리가 '합리적 선택'에 있어서 핵심적인 개념이다.
    + 행위자들은 자신들의 선호가 무엇인지를 규정할 수 있어야 하고(need to be able to identify), 나아가 그 선호에 따라서 행동하게 된다.
    
  + 전략
    + 우리가 확인할 수 있는 행동들은 행위자들이 자신에게 있어서 최선의 결과를 달성하기 위하여 취한 행동들이다.
    + 무엇이 행위자들로 하여금 지배적인 전략(dominant strategy, 이하 지배전략)을 가지게끔 만들까?
      + 행위자의 다른 전략들이 더 이상 중요하지 않을 때, 우리는 지배전략이 존재한다고 말한다.
      + 즉, 지배전략이란 어떤 행위자가 게임의 상대방이 무슨 행동을 취하던 간에 그와 상관없이 항상 같은 선택을 하게 만드는 전략을 의미한다.
  
  + 해결방안
    + 게임은 퍼즐과도 같다.
      + 우리는 우리가 살아가고 있는 이 현실세계를 조금이라도 더 잘 이해할 수 있도록 돕는 해결방안, 답을 찾아 해멘다.
      + 게임이론가들에게 있어서 해를 찾는다고 하는 것은 곧 균형(equilibria)을 찾는다는 것을 의미한다.
    + 균형은 게임의 두 행위자 모두가 최선의 전략을 수행하고 있을 때 나타나는 결과를 의미한다.
      + 따라서 균형이란 필연적으로 다른 플레이어의 행동에 대한 반응이라고 할 수 있다.

우리는 게임이론을 다음과 같은 접근법을 통해 이해하고자 한다.

1. 먼저, 행위자가 누구인지, 몇인지를 규명하고
2. 그 행위자들에게 있어서 가능한 전략을 규명한다. 대개는 '협력'(coperate)과 '승패'(defect)와 관련된 것들이다.[^3-3]
3. 행위자들의 선호에 값(values)을 붙여서 순위를 매긴다.
4. 해를 찾는다.

그럼 실제 게임의 사례를 한 번 살펴보자.
I.S.를 진압해야 하는 상황이 주어졌다고 하자. 두 플레이어는 각각 미국과 러시아이고, 이들은 I.S.를 진압해야 한다고는 생각하지만 독박은 쓰기 싫은 상황이다. 만약 자기가 먼저 나서지 않았는데, 상대방이 나서서 비용을 다 부담해준다면 그게 제일 좋은 상황일 것이다.

|      	|      	|              	      | 러시아 |                      	|
|:----:	|:----:	|:------------------:	|:-----: |:--------------------:	|
|      	|      	| 주도               	|        | 대기                 	|
|     	| 주도 	| 상호 협력하여 진압 	|        | 러시아에게 유리     	  |
| 미국 	|      	| (3,3) 	            |        | (1,4)               	  |
|      	| 대기 	| 미국에게 유리     	|        | 서로 진압문제를 무시   |
|      	|     	| (4,1)             	|        | (2,2)	                  |
Table: 게임1. 누가 I.S.를 진압할 것인가?

이때, 미국의 선호순위는 다음과 같을 것이다.

  + 미국에게 유리한 경우(4) > 상호 협력하여 진압할 경우(3) > 서로 무시할 경우(2) > 러시아에게 유리할 경우(1)
  
러시아의 선호순위는 다음과 같을 것이다.

  + 러시아에게 유리한 경우(4) > 상호 협력하여 진압할 경우(3) > 서로 무시할 경우(2) > 미국에게 유리할 경우(1)
  
선택의 쌍이 (미국, 러시아)로 이루어져 있다고 할 때, 여기서 미국의 지배전략은 대기하는 것이다. 왜냐하면 주도와 대기 중에서는 대기하는 쪽이 주도하는 쪽에 비해 모두 높은 선호를 가지고 있기 때문이다. 러시아 역시 마찬가지이다. 러시아의 지배전략도 대기하는 것이다.

  + 따라서 이 두 행위자의 지배전략이 교차하는 부분은 "서로 진압을 무시"하는 것이다.
    + 바로 이 두 행위자의 전략이 서로 변화하지 않는 지점, 내쉬 균형(Nash Equilibrium)이 된다. 
      + 구체적으로 내쉬 균형이란 각 행위자가 서로의 전략에 대해 최선의 대응을 하고 있다는 것으로 게임이 균형 상태에 있다는 것을 의미한다.
    + 그런데 사실 선택에 따른 선호 결과의 조합이 가장 높은 값을 지니는 것은 "상호 협력하여 진압"하는 것(3, 3)이다. 
    + 이러한 최고의 선호 조합의 값을 지니는 경우를 파레토 최적점(Pareto optimal)이라고 한다.
      + 파레토 최적과 파레토 차선(suboptimal)
        + 파레토 최적: 협력이 파레토 최적의 결과를 가져올 수 있다. 상호 혜택이 최선인 경우, 결합 효용(joint utility)가 가장 높은 경우
        + 파레토 차선: 승패를 가를 때가 파레토 차선이라고 할 수 있다. 즉, 두 행위자의 선택지가 결합되는 것이 현실화되지 않을 경우
    + 따라서 이 게임에서 우리는 두 행위자들의 지배전략이 교차하는 내쉬 균형이 반드시 두 행위자에게 최적의 결과를 가져오지는 않는다는 것을 확인할 수 있다.
  
### 죄수의 딜레마 극복하기 (Overcoming the Prisoner's Dilemma)

죄수의 딜레마에 대해 논의하기에 앞서서 하나의 [영상](https://www.youtube.com/watch?v=p3Uos2fzIJ0)을 보자.

  + 위의 유튜브 영상에서 게임이 어떻게 전개될지에 영향을 미칠 수도 있는 변화들로는 어떤 것들이 있을까?
    + 만약 호스트가 게임에 개입하여 게스트 모두에게 질문을 던졌다면 어떻게 되었을까?
    + 만약 동일한 게임을 다시 한 번 플레이해야 한다면 어떻게 될까?
  
  + 죄수의 딜레마의 전제는 바로 여기에 있다.
    + 국제체제에서 협력을 달성하기 위해서는 유인(incentives)을 변화시켜야만 한다.
    + 행위자들에게 있어서 계속 패배하는 것보다는 협력하는 것이 더 선호할만한 선택지가 되어야 한다.
    + 무엇이 행위자들의 유인을 변화시킬 수 있는가? $\rightarrow$ 여기서 제도(institutions)의 역할을 생각해볼 필요가 있다.

이번에는 죄수의 딜레마가 아니라 다른 유형의 게임을 생각해보자.

### 국제관계에서의 치킨 게임(Chicken Game in IR)

|      	|      	|              	      | 이란   |                      	|
|:----:	|:----:	|:------------------:	|:-----: |:--------------------:	|
|      	|      	| 저지               	|        | 유지                 	|
|     	| 저지 	| 양국 간 긴장의 완화 |        | 이란에게 유리      	  |
| 미국 	|      	| (3,3) 	            |        | (2,4)               	  |
|      	| 유지 	| 미국에게 유리	      |        | 전쟁?                  |
|      	|     	| (4,2)             	|        | (1,1)	                |
Table: 게임2. 핵무기 경쟁

이때, 미국의 선호순위는 다음과 같을 것이다.

  + 미국에게 유리한 경우(4) > 양국 간 긴장의 완화(3) > 이란에게 유리한 경우(2) > 전쟁(1)
  
이란의 선호순위는 다음과 같을 것이다.

  + 이란에게 유리한 경우(4) > 양국 간 긴장의 완화(3) > 미국에게 유리한 경우(2) > 전쟁(1)

각 행위자들의 지배전략은 무엇인가? 치킨게임에서는 존재하지 않는다. 그렇다면 두 행위자들이 행동을 변화시킬 유인이 존재하지 않는, 균형적 결과는 무엇인가? 바로 이란에게 유리한 경우와 미국에게 유리한 경우, 두 가지이다. 이 게임에서는 선호의 순위가 바뀌었기 때문에 전쟁이 아닌 모든 결과는 파레토 최적의 결과이다. 긴장 완화, 미국 유리, 이란 유리 모두 두 국가의 결과는 선호의 총합 6으로 동일하다.

  + 여기서의 결과는 각각의 행위자가 다른 행위자들에 대해 어떻게 믿고 있느냐에 좌우된다.
  + 즉, 치킨게임을 통해 우리는 국제관계 속에서 명성(reputation)과 정보(information)이 특히 중요하다는 것을 알 수 있다.
    + 위기를 무릅쓸 유인을 감소시키는 것(de-incentivize risk)이 중요하다!
    + 정보의 공유는 치킨게임에서의 위험을 완화시킬 수 있는 하나의 방법이다.

### 게임이론으로 생각해보는 브렉시트(Brexit)

|      	|      	|              	      | E.U.   |                      	|
|:----:	|:----:	|:------------------:	|:-----: |:--------------------:	|
|      	|      	| 교섭               	|        | 결렬                 	|
|     	| 교섭 	| 효율적인 무역/여행  |        | E.U. 주도의 규제    	  |
| 영국 	|      	| (4,4) 	            |        | (1,3)               	  |
|      	| 결렬 	| 영국 주도의 규제    |        | 비효율적인 무역/여행   |
|      	|     	| (3,1)             	|        | (2,2)	                |
Table: 게임3. 브렉시트

이때, 영국의 선호순위는 다음과 같을 것이다.

  + 효율적인 무역/여행(4) > 영국 주도의 규제(3) > 비효율적인 무역/여행(2) > E.U. 주도의 규제(1)
  
E.U.의 선호순위는 다음과 같을 것이다.

  + 효율적인 무역/여행(4) > E.U. 주도의 규제(3) > 비효율적인 무역/여행(2) > 영국 주도의 규제(1)

이 게임에서 각 행위자의 지배전략은 치킨게임과 마찬가지로 존재하지 않는다. 그렇다면 균형은? 효율적인 무역/여행 또는 비효율적인 무역/여행으로 두 개의 균형이 존재한게 된다. 이때, 효율적인 무역/여행이 두 행위자 모두에게 최선의 결과를 약속하므로 파레토 최적의 해라고 할 수 있다.

이러한 게임의 양태를 사슴사냥(stag hunt)라고도 한다. 즉, 공동의 이익을 위하여 협력하는 것이 이득이 되는 게임을 말하는데, 사슴사냥 게임에서 중요한 것은 바로 신뢰이다. 

  + 과연 행위자들이 다른 행위자를 얼마나 믿을 수 있는가?
  + 같이 쫓기로 한 사슴을 계속 쫓을 것이라고 믿을 수 있는가? 혹은 다른 행위자가 이탈하여 토끼를 잡고 나는 사슴을 놓치는 불신의 상황을 고려하여 나도 토끼를 잡으러 가야 할까? (From Efficient to Inefficient)
  + 신뢰를 제고하고 협력을 가능하게 하는 방법들로는 어떠한 것이 있을까?
    + 상호 의사결정에 드는 비용이 더 작을수록, 그리고 협력의 실패의(승패를 가르는) 비용이 더 클수록 행위자들은 협력에 관심을 가지게 된다.
    
### 제도의 역할: 제도는 국가들로 하여금 속임수를 쓸 선택지를 최소화시킨다.

앞서 언급한 행위자를 제약할 수 있는 기제, 제도에 대해 다시 한 번 읽어보자.


  
[^3-1]: 대부분의 비교정치, 혹은 법정치(judicial politics)에서는 이를 헌법적이라고 번역하겠지만 국제관계는 무정부 상태에고 국제관계 전체를 규율하는 법중의 법, 헌법은 존재하지 않기에 다음과 같이 번역하였다.
[^3-2]: 번역하자면 모형이라고 할 수 있을 것이다. 우리는 모형을 통해 현실세계의 주요 구성단위와 단위 간 관계, 총체적 구조를 파악한다. 여기서 모형과 모델은 동의어이며 상호교환이 가능한 개념으로 사용한다.력
[^3-3]: 굳이 표현하자면 협력 혹은 승패라는 행위에서 약간씩 다른(variation) 전략들이 존재할 수 있다. 대표적으로 거래(bargaining)이라던지.
